# fly.toml file generated for microscop

app = "microscop"
primary_region = "sjc"

[build]
  image = "nginx:alpine"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
